# SPDX-FileCopyrightText: Contributors to osm-powerplants
#
# SPDX-License-Identifier: MIT

"""
Regional country groupings for global OSM power-plant extraction.

The global dataset is produced by extracting each region independently (in
parallel CI jobs) and merging the regional outputs. Splitting by region keeps
any single Overpass run from exceeding practical time limits and lets us
regenerate individual regions without re-fetching the world.

Groupings follow the UN M49 geoscheme with two pragmatic deviations:
    - Cyprus is placed in ``europe`` (as in EU membership) rather than
      Western Asia.
    - ``russia`` is carved out as a standalone region because Russia alone
      is heavier than several M49 regions combined.

All country names are resolvable via ``pycountry.countries.lookup`` and are
consumed by ``osm_powerplants.interface.validate_countries``. Kosovo is
intentionally absent: it cannot be queried via Overpass and is handled via
the ``omitted_countries`` key in config.yaml, not here.
"""

REGIONS: dict[str, list[str]] = {
    "europe": [
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Cyprus",
        "Czechia",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "Germany",
        "Gibraltar",
        "Greece",
        "Guernsey",
        "Holy See (Vatican City State)",
        "Hungary",
        "Iceland",
        "Ireland",
        "Isle of Man",
        "Italy",
        "Jersey",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Svalbard and Jan Mayen",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom",
        "Åland Islands",
    ],
    "russia": [
        "Russian Federation",
    ],
    "north_america": [
        "Bermuda",
        "Canada",
        "Greenland",
        "Saint Pierre and Miquelon",
        "United States",
    ],
    "central_america_caribbean": [
        "Anguilla",
        "Antigua and Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Belize",
        "Bonaire, Sint Eustatius and Saba",
        "British Virgin Islands",
        "Cayman Islands",
        "Costa Rica",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Grenada",
        "Guadeloupe",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Jamaica",
        "Martinique",
        "Mexico",
        "Montserrat",
        "Nicaragua",
        "Panama",
        "Puerto Rico",
        "Saint Barthélemy",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin (French part)",
        "Saint Vincent and the Grenadines",
        "Sint Maarten (Dutch part)",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "Virgin Islands, U.S.",
    ],
    "south_america": [
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Falkland Islands (Malvinas)",
        "French Guiana",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
    ],
    "northern_africa": [
        "Algeria",
        "Egypt",
        "Libya",
        "Morocco",
        "Sudan",
        "Tunisia",
        "Western Sahara",
    ],
    "western_africa": [
        "Benin",
        "Burkina Faso",
        "Cabo Verde",
        "Côte d'Ivoire",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Liberia",
        "Mali",
        "Mauritania",
        "Niger",
        "Nigeria",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Senegal",
        "Sierra Leone",
        "Togo",
    ],
    "middle_africa": [
        "Angola",
        "Cameroon",
        "Central African Republic",
        "Chad",
        "Congo",
        "Congo, The Democratic Republic of the",
        "Equatorial Guinea",
        "Gabon",
        "Sao Tome and Principe",
    ],
    "eastern_africa": [
        "British Indian Ocean Territory",
        "Burundi",
        "Comoros",
        "Djibouti",
        "Eritrea",
        "Ethiopia",
        "Kenya",
        "Madagascar",
        "Malawi",
        "Mauritius",
        "Mayotte",
        "Mozambique",
        "Réunion",
        "Rwanda",
        "Seychelles",
        "Somalia",
        "South Sudan",
        "Tanzania",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ],
    "southern_africa": [
        "Botswana",
        "Eswatini",
        "Lesotho",
        "Namibia",
        "South Africa",
    ],
    "western_asia": [
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Georgia",
        "Iraq",
        "Israel",
        "Jordan",
        "Kuwait",
        "Lebanon",
        "Oman",
        "Palestine, State of",
        "Qatar",
        "Saudi Arabia",
        "Syria",
        "Türkiye",
        "United Arab Emirates",
        "Yemen",
    ],
    "central_asia": [
        "Kazakhstan",
        "Kyrgyzstan",
        "Tajikistan",
        "Turkmenistan",
        "Uzbekistan",
    ],
    "southern_asia": [
        "Afghanistan",
        "Bangladesh",
        "Bhutan",
        "India",
        "Iran",
        "Maldives",
        "Nepal",
        "Pakistan",
        "Sri Lanka",
    ],
    "southeastern_asia": [
        "Brunei Darussalam",
        "Cambodia",
        "Indonesia",
        "Laos",
        "Malaysia",
        "Myanmar",
        "Philippines",
        "Singapore",
        "Thailand",
        "Timor-Leste",
        "Vietnam",
    ],
    "eastern_asia": [
        "China",
        "Hong Kong",
        "Japan",
        "Macao",
        "Mongolia",
        "North Korea",
        "South Korea",
        "Taiwan",
    ],
    "oceania": [
        "American Samoa",
        "Australia",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Cook Islands",
        "Fiji",
        "French Polynesia",
        "Guam",
        "Kiribati",
        "Marshall Islands",
        "Micronesia, Federated States of",
        "Nauru",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands",
        "Palau",
        "Papua New Guinea",
        "Pitcairn",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
        "Wallis and Futuna",
    ],
}


def get_region(name: str) -> list[str]:
    """Return the country list for a region, raising a helpful error if unknown.

    Parameters
    ----------
    name : str
        Region key (e.g. ``"europe"``, ``"southeastern_asia"``).

    Returns
    -------
    list[str]
        Country names resolvable by ``pycountry.countries.lookup``.
    """
    try:
        return REGIONS[name]
    except KeyError:
        available = ", ".join(sorted(REGIONS))
        raise KeyError(f"unknown region '{name}'. available: {available}") from None
